"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-20

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # NOTE: Full schema is generated via `alembic revision --autogenerate` on
    # first boot. This migration primarily ensures the pgvector extension is
    # available before autogenerated migrations create KB chunk tables.


def downgrade() -> None:
    pass
